### ISSUE TITLE
A solution for TouchCursor on MacOS

### ISSUE THREAD

**Issue by AlienKevin** [donniebreve/touchcursor-mac#1]
Since the port for MacOS hasn't been worked out, I tinkered around and made a solution using the open source automation tool [hammerspoon](https://www.hammerspoon.org/). If you are interested, [give it a try here](https://github.com/AlienKevin/touchcursor-macos). I'd love some feedbacks and hopefully work together to finally bring the full TouchCursor experience to MacOS!

**Comment by donniebreve** [comment]
Sorry I missed this so long ago, but I've finally had someone push me to finish this port. It's definitely alpha state, but working with #2.

**Comment by AlienKevin** [comment]
Wow that's awesome! I'm definitely interested in whether a more native solution can out perform Hammerspoon's Lua script.
