### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by cprovatas** [donniebreve/touchcursor-mac#15]
What are these keys?  They don't compile when I check out project

<img width="535" alt="Screen Shot 2022-05-13 at 7 13 01 PM" src="https://user-images.githubusercontent.com/14881080/168407060-be552783-3811-4a41-b3e0-f231aa390242.png">

**Comment by cprovatas** [comment]
I Will probably just delete them, but would be helpful to add to readme if other people have the problem

**Comment by cprovatas** [comment]
#defines commented out for some reason...

**Comment by cprovatas** [comment]
https://github.com/donniebreve/touchcursor-mac/pull/16

**Comment by donniebreve** [comment]
These are standard keys defined in the Linux kernel. macOS doesn't support a large portion of them though. Everything that's commented out in the `keys.h` file should also be commented out in the `keys.c` file. I would be happy to take a separate PR with those changes.

**Comment by donniebreve** [comment]
This should be fixed with 02f35660bbc6dd1e365f2485577cfb19a7b51fb0.
