### ISSUE TITLE
Can you provide some install instructions?

### ISSUE THREAD

**Issue by SurajMeena** [donniebreve/touchcursor-mac#21]
Hi, can you provide some install instructions for mac. I am new to mac and I even tried xcode to build release variant of it but still couldn't run the application

**Comment by donniebreve** [comment]
Hello @SurajMeena , there aren't any install instructions because this application doesn't have an installer (yet). You have to run the application in xcode with elevated permissions.

**Comment by SurajMeena** [comment]
Hi @donniebreve , I was able to build release variant from xcode by going to product -> edit schema and then selecting release. When I launch the release variant I can see there is an icon in menu but it doesn't show any device listed. What can be possible reason for that?
