### ISSUE TITLE
Create some sort of GUI

### ISSUE THREAD

**Issue by donniebreve** [donniebreve/touchcursor-mac#6]
The compiled app launches in a terminal window. How can the app simply run in the background?

**Comment by jasonmlkang** [comment]
Steps to launch the compiled app in terminal:

1. from xcode, press "_**cmd ,**_" together to bring up preference menu
2. under _**locations**_ tab, enter a custom path to _**Derived Data**_ (e.g. touchcursor-mac/build)
3. close preference menu, compile source code, right click on _**touchcursor-mac**_, from the dropdown menu click _**Show in Finder**_
4. bring up Mac OS System Preference --> Security & Privacy --> Privacy tab, click _**Accessibility**_, add and enable terminal to control your computer
5. from the same tab as above, click _**Input Monitoring**_, add and enable terminal to control your computer
6. open terminal, cd to the path to derived data, find touchcursor-mac executable (e.g. touchcursor-mac/build/touchcursor-mac-cwjkmctt/Build/Products/Debug/touchcursor-mac)
7. type `sudo ./touchcursor-mac` to execute (note. sudo is necessary to use HDI library)

**Comment by jasonmlkang** [comment]
@donniebreve pls very the steps from above on your environment

**Comment by donniebreve** [comment]
I think step 4 is what I want to avoid. It's like the output binary requires being run in a terminal. Maybe it's because the project output type is not correct?

Ideally step 4/5 you would be adding the binary, not terminal.

**Comment by jasonmlkang** [comment]
@donniebreve I think this has to do with project type. I will experiment with it.

**Comment by Fizol** [comment]
@jasonmlkang I followed your instructions and it doesn't work. I also added all mentioned permission to the touchcursor-mac executable. My MacOS is 10.15.7. Can I try something else?

**Comment by jasonmlkang** [comment]
FYI, we're working on an installer to make this process easier.

To answer your question, I need have some context of where it fails.
Does it fail at the build stage or execution stage? Also, do you use external keyboard?

**Comment by jasonmlkang** [comment]
> @jasonmlkang I followed your instructions and it doesn't work. I also added all mentioned permission to the touchcursor-mac executable. My MacOS is 10.15.7. Can I try something else?

@Fizol 
FYI, we're working on an installer to make this process easier.

To answer your question, I need have some context of where it fails.
Does it fail at the build stage or execution stage? Also, do you use external keyboard?

**Comment by Fizol** [comment]
@jasonmlkang Ok, I got it running. I had modified the `appleProductID` to suite my device:
```
Device: Apple Internal Keyboard / Trackpad
Serial: ####
Manufacturer: Apple Inc.
ProductID: 832, VendorID: 1452, LocationID: ####
```
Then I ran it from terminal and I got this log `Capturing the MacOS Internal Keyboard... Success`, but it doesn't interact with keyboard as expected. Spacebar+i,j,k,l etc. are not giving the expected behaviour.
Lack of config file could be a reason? Actually, it displayed `error: could not open the configuration file` as well.

**Comment by jasonmlkang** [comment]
@Fizol 
You figured out. Great job!
Pls use the config file from here https://github.com/donniebreve/touchcursor-linux/blob/master/touchcursor.conf
Copy-and-paste the config file to `~/.config/touchcursor/touchcursor.conf`

**Comment by donniebreve** [comment]
@Fizol I'm glad you got it working, and I know keyboard selection is currently a pain point, but I would like to keep this issue on topic for making the application run as a background process. If you run into any more troubleshooting problems, feel free to open a new issue.

That being said, here's some relevant reading: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/DesigningDaemons.html#//apple_ref/doc/uid/10000172i-SW4-BBCBHBFB

**Comment by Fizol** [comment]
@jasonmlkang Thanks, now it works
@donniebreve Sure 🙂
