### ISSUE TITLE
App needs some sort of keyboard selector

### ISSUE THREAD

**Issue by donniebreve** [donniebreve/touchcursor-mac#7]
It would be nice if the app had a keyboard selector menu option.

**Comment by jasonmlkang** [comment]
Articles about playing with unsafe and unmanaged variables in swift:
* https://www.raywenderlich.com/7181017-unsafe-swift-using-pointers-and-interacting-with-c
* https://www.vadimbulavin.com/swift-pointers-overview-unsafe-buffer-raw-and-managed-pointers/
